### PR TITLE
Add PIPY and update README

### PR DESCRIPTION
**Pull request by truskovskiyk**

### CODE REVIEW

**Comment by benjaminye** [comment]
@truskovskiyk @RohitSaha 

I would also make `llmtune` as the entry point for running the CLI. Instead of doing `python toolkit.py --config-path config.yaml`, users can just do `llmtune --config-path config.yaml`. We can also add a `pipx` installation instruction so CLI lives in an isolated virtual environment.

I have made the following changes in my local machine and can verify it works.
1. Move `toolkit.py` into `llmtune/cli/tookit.py`
2. Modify the entrypoint in `toolkit.py`
```diff
- if __name__ == "__main__":
-     app()

+ def cli():
+     app()
```
4. Add script entry point in `pyproject.toml`
```diff
+ [tool.poetry.scripts]
+ llmtune = "llmtune.cli.toolkit:cli"
```

**Review by benjaminye — APPROVED** [review]
Looks good! Please take a look at comment https://github.com/georgian-io/LLM-Finetuning-Hub/pull/115/#issuecomment-2033391618.

Also, any reason of using twine vs [poetry publish](https://python-poetry.org/docs/cli/#publish)?

**Comment by benjaminye** [comment]
Related: https://github.com/georgian-io/LLM-Finetuning-Hub/issues/108

**Comment by truskovskiyk** [comment]
> @truskovskiyk @RohitSaha
> 
> I would also make `llmtune` as the entry point for running the CLI. Instead of doing `python toolkit.py --config-path config.yaml`, users can just do `llmtune --config-path config.yaml`. We can also add a `pipx` installation instruction so CLI lives in an isolated virtual environment.
> 
> I have made the following changes in my local machine and can verify it works.
> 
> 1. Move `toolkit.py` into `llmtune/cli/tookit.py`
> 2. Modify the entrypoint in `toolkit.py`
> 
> ```diff
> - if __name__ == "__main__":
> -     app()
> 
> + def cli():
> +     app()
> ```
> 
> 4. Add script entry point in `pyproject.toml`
> 
> ```diff
> + [tool.poetry.scripts]
> + llmtune = "llmtune.cli.toolkit:cli"
> ```

good idea, please create issue

**Pull request merged**
