### PR TITLE
Fix/issuse 34 docker

### PR DESCRIPTION
**Pull request by anthonyprinaldi**
This PR is meant to address #34. 

It adds a bash script for fine-tuning to make working with the Dockerfile easier. It also provides the Dockerfile itself, and the compose.yaml that specifies how to run the Docker container. 

The README is updated to explain the new files.

Some items are added to .gitignore too which arose when testing the fine-tuning scripts.

*Note: this solution only works for fine-tuning using the existing dataset included in the repo. The next step will be to include an input file (formatted in the correct way) that can be used for fine-tuning on a custom dataset.*

### CODE REVIEW

**Review by mariia-georgian — COMMENTED** [review]
@anthonyprinaldi thanks for the contribution! I tried to run docker-compose command `MODEL="flan-t5" TASK="classification" PYTHON_ARGS="--peft_method prefix --prefix_tokens 20 --epochs 5" docker compose up` and it got stuck on training, I don't see the progress going.  When I tried to simply run python file, it worked fine.
Screenshot 2023-10-25 at 3 30 54 PM

**Comment by anthonyprinaldi** [comment]
Apologies, previously I didn't have a GPU system so couldn't test out the run. 

Things become a bit difficult trying to run docker with GPUs, there are a lot of prerequisites: [https://blog.roboflow.com/nvidia-docker-vscode-pytorch/](https://blog.roboflow.com/nvidia-docker-vscode-pytorch/).

However, I will update the docker files so they work in the case that one has met all the requirements.

**Comment by anthonyprinaldi** [comment]
The above error may also have happened since it was not using GPU so no progress was being made.

**Comment by anthonyprinaldi** [comment]
@mariia-georgian I've pushed a couple of changes with the docker files. Try running it again with the command:

```
MODEL="flan-t5" TASK="classification" PYTHON_ARGS="--peft_method prefix --prefix_tokens 20 --epochs 5" docker compose run mlflow
```

**Comment by mariia-georgian** [comment]
@anthonyprinaldi thanks a lot for the update! I tried to run it but takes about 1 h (more than that it seems) to pull a docker image 
Screenshot 2023-10-31 at 2 12 02 PM

Is it possible to speed up the process somehow?

**Comment by mariia-georgian** [comment]
@anthonyprinaldi thanks a lot for the changes you made to the PR! It does work on the GPU now!

**Comment by anthonyprinaldi** [comment]
@mariia-georgian I noticed that as well. I think part of it is due to the number of requirements needed to get things working with the GPU. I'll look into it and see if I can decrease the size of the image / remove redundant packages.

**Pull request closed without merging**
